Lion-Craft/Tinyinfo

- Tinyinfo/MainWindow.cs
Added Motherboard Manufacturer, Model and Serial number information, see #4
> Added Motherboard information

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
System information is now loaded when the program starts
> Added info load on startup

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
Added checkbox which enables Always on Top when checked, see #9
> Added Always on Top checkbox

- Tinyinfo/MainWindow.cs
> 5 graphics carddispaly adapter info

- Tinyinfo/MainWindow.cs
Reduced amount of code needed for loading info on startup
> 17 simplify load code

- Tinyinfo/MainWindow.cs
Display adapter info now loads again
> Fixed graphics info not loading

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
> Update Menubar dev branch

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/MainWindow.resx
- Tinyinfo/SettingsWindow.Designer.cs
- Tinyinfo/SettingsWindow.cs
- Tinyinfo/SettingsWindow.resx
- Tinyinfo/Tinyinfo.csproj
- Tinyinfo/packages.config
added menu bar, settings window, theme settings, about window and link to github page
> 12 menubar

- Tinyinfo/MainWindow.cs
Added battery info and removed debug counter
> 3 battery info

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/MainWindow.resx
- Tinyinfo/SettingsWindow.Designer.cs
- Tinyinfo/SettingsWindow.cs
Renamed form buttons and textboxes aswell as their methods.
> 39 improve form object naming

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
Added Refresh menu bar button to allow manually refreshing system info
> Added Refresh menubar item

- Tinyinfo/MainWindow.cs
> 1 drive info

- Tinyinfo/MainWindow.cs
Section titles are now output before their foreach loop.
Affected Titles:
- CPU
- Motherboard
- BIOS
> Section titles no longer being output from within foreach

- Tinyinfo/MainWindow.cs
Memory section whitespace has been reduced.
> Fixed Memory section whitespace

- Tinyinfo/MainWindow.cs
Added basic Network Adapter info
> 28 network adapter info

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
> Remove play/pause button

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/Tinyinfo.csproj
- Tinyinfo/packages.config
I also modified two small things: both the button for the plain text and json will call the same function (DRY). XML I don't think it makes sense, but still.
This solves partially issue #60
> Added button to export as JSON :)

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/Tinyinfo.csproj
Added additional GPU Info for Nvidia GPUs using NvAPIWrapper
> 96 use nvapiwrapper for nvidia gpu information

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/SettingsWindow.Designer.cs
- Tinyinfo/SettingsWindow.cs
Added a Font selector which allows the user to set a custom font
> 90 font selection

- Tinyinfo/JSON.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/Tinyinfo.csproj
- Tinyinfo/packages.config
> Rewrite of JSON export: basic functionality

- Tinyinfo/JSON.cs
- Tinyinfo/MainWindow.cs
Finished rewriting the JSON Export which is part of #60
> Rewrite of JSON Export

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
- Tinyinfo/Tinyinfo.csproj
- Tinyinfo/XML.cs
Added XML Export and thus closes #60
> #60 Added XML Export

- Tinyinfo/MainWindow.cs
Fixes #134 by increasing max video device amount to 8 which should be enough for most systems.
> 134 error when starting

- Tinyinfo/MainWindow.cs
- Tinyinfo/SettingsWindow.cs
Removed Transparent Splash setting from tinyinfo.ini generation.
> Removed unused setting from micro ini file

- Tinyinfo/MainWindow.cs
Fixes #147 for the micro version, #149 for the full version
> Add try catch to info refresh - micro version

- Tinyinfo/MainWindow.Designer.cs
- Tinyinfo/MainWindow.cs
> 112 OS Info - Micro Version
